In [36]:
import os
from glob import glob
import pandas as pd
import numpy as np

In [48]:
A = []

In [49]:
B = np.array([[1, 0, 0], [0, 0, 0]])
C = np.array([[1, 0, 0], [0, 0, 0]])

In [50]:
A.append(B)
A.append(C)

In [63]:
np.concatenate(A)

array([[1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [61]:
np.concatenate((B, C))

array([[1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [7]:
base_dir = os.getcwd()
file_list = glob(os.path.join(base_dir, '*.csv'))

In [18]:
base_dir

'/home/sks/COMPETITION/DACON/computer_vision2/submit'

In [25]:
labels = []
for file in file_list:
    tmp_tb = pd.read_csv(file)
    labels.append(tmp_tb.iloc[:, 1:].values)

In [26]:
agg = np.mean(labels, axis=0)
agg_result = np.where(agg > 0.5, 1, 0)

In [28]:
agg_result

array([[1, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [1, 1, 0, ..., 1, 1, 1]])

In [31]:
submission_file = pd.read_csv('/home/sks/COMPETITION/DACON/computer_vision2/dataset/sample_submission.csv')
#prob_file = submission_file.copy()

# Predictions / Submit
submission_file.iloc[:, 1:] = agg_result
#prob_file.iloc[:, 1:] = np.array(fin_probs)

In [32]:
submission_file

      index  a  b  c  d  e  f  g  h  i  ...  q  r  s  t  u  v  w  x  y  z
0     50000  1  0  1  0  1  1  0  1  1  ...  0  0  0  1  1  0  0  1  0  1
1     50001  0  0  0  0  1  0  1  0  1  ...  0  1  0  0  1  1  1  0  0  0
2     50002  0  0  1  1  1  0  1  1  1  ...  0  1  1  0  1  0  1  0  0  1
3     50003  1  1  0  0  0  1  1  0  0  ...  0  1  0  1  0  0  0  1  1  1
4     50004  0  0  1  0  1  1  0  0  0  ...  1  0  1  1  1  0  1  0  0  0
...     ... .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
4995  54995  0  1  1  1  0  0  0  1  0  ...  0  1  0  1  0  0  1  0  1  1
4996  54996  1  1  1  0  0  0  1  0  1  ...  1  0  1  0  0  0  0  1  0  1
4997  54997  1  0  0  1  0  1  0  0  0  ...  0  0  0  1  1  1  1  0  0  1
4998  54998  0  0  1  0  0  0  1  1  1  ...  1  1  0  1  0  1  1  0  0  1
4999  54999  1  1  0  0  0  1  0  0  1  ...  0  1  1  0  0  0  1  1  1  1

[5000 rows x 27 columns]

In [35]:
save_path = os.path.join(base_dir, f'submission_model_ensemble_0.csv')
#save_path_prob = os.path.join(args.base_dir, f'submit/submission_model_{args.model_index}_prob.csv')

submission_file.to_csv(save_path, index=False)